### ISSUE TITLE
NewTracker conda environment build fails

### ISSUE THREAD

**Issue by mariakesa** [oist/Usiigaci#15]
Hello!

Thank  you so much for the wonderful software! I'm trying to get it to work:-)

When installing from the python_packages_2019-05-09.txt I get the following error

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/openblas-0.3.6-h6e990d7_1.tar.bz2>
Elapsed: 00:00.604552
CF-RAY: 5d5e53cf8b1cdfef-FRA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/qt-5.9.7-h52cfd70_1.tar.bz2>
Elapsed: 00:00.237902
CF-RAY: 5d5e55adba046455-FRA

Any help would be appreciated!

Thank you:-)

Maria

**Comment by hftsai** [comment]
Hi Maria,
how about if you just conda install openblas==0.3.6 qt==5.9.7

does it work?
I tried before and seemed to work. sometimes the conda forge library changes abit

Do remember to replace the imageItem.py in pyqtgraph and also change the subnetlinker's max_candidate as stipulated in the note.txt
