### ISSUE TITLE
PB with cell tracking

### ISSUE THREAD

**Issue by Romain-Morichon** [oist/Usiigaci#18]
Hello,
i try to use usiigacy with the cell tracking part. I've installed anaconda tu run ussigaci. when i try to open the folder to test the cell tracking, i've got this error.
![error](https://user-images.githubusercontent.com/79698781/109294923-2b95d300-782e-11eb-973f-86aec7758de0.jpg)

I've just started python programming so take it easy with the explanation :-)

Have a nice day

Romain

**Comment by carmilla94** [comment]
Hi, 
I am having he same problem.  Have you find the solution?

Have a nice day,

Carmen

**Comment by Romain-Morichon** [comment]
Unfortunatly, I still have this problem. Actually, i use active contour with the software ICY to make the tracks and tracking manager in ICY to have differents parameters.

have a nice day

Romain

**Comment by carmilla94** [comment]
Tru to change pims_sequence = pims.ImageSequence(join(path, '*.{}'.format(file_extension)), process_func=None)  for pims_sequence = pims.ImageSequence(join(path, '*.{}'.format(file_extension))) in cell_io.py

**Comment by Romain-Morichon** [comment]
Thx a lot! It's works now!!
