### ISSUE TITLE
failed to create mask folder & failed to deploy the inference, skipping...

### ISSUE THREAD

**Issue by hiroalchem** [oist/Usiigaci#3]
I had error below
>Loading model from:  trained_network/Usiigaci_1.h5
prediction for:  /home/Usiigaci/test/T98G_sample
model run 1 of 3
failed to create mask folder
 97%|#########################################8 | 37/38 [00:49<00:01,  1.33s/it]failed to deploy the inference, skipping...
>Loading model from:  trained_network/Usiigaci_2.h5
prediction for:  /home/Usiigaci/test/T98G_sample
model run 2 of 3
failed to create mask folder

  0%|                                                    | 0/38 [00:00<?, ?it/s]^Cfailed to deploy the inference, skipping...
>Loading model from:  trained_network/Usiigaci_3.h5
prediction for:  /home/Usiigaci/test/T98G_sample
model run 3 of 3
failed to create mask folder

**Comment by hftsai** [comment]
Hi I observed this some time on particular machine. 
It could be due to the inference script was looking at the log text. 

if you don't need to log the output

try comment out line 318
#sys.stdout=Logger()

See if it is resolved.
Please do let me know

**Comment by hiroalchem** [comment]
Thank you for your reply.
I commented out line 318 however, I still got stuck like below
----------
prediction for:  /home/hkawai/obj/Usiigaci/test2/T98G_sample
model run 1 of 3
 97%|#########################################################################################################################################2   | 37/38 [00:54<00:01,  1.46s/it]failed to deploy the inference, skipping...
>Loading model from:  trained_network/Usiigaci_2.h5
prediction for:  /home/hkawai/obj/Usiigaci/test2/T98G_sample
model run 2 of 3

 11%|##############9 
------------------
and when I stopped it with "ctrl +c"
------------------
 to deploy the inference, skipping...
>Loading model from:  trained_network/Usiigaci_3.h5
prediction for:  /home/Usiigaci/test2/T98G_sample
model run 3 of 3
Exception ignored in: <object repr() failed>.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 887, in __del__
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 1098, in close
    if self.disable:
AttributeError: 'tqdm' object has no attribute 'disable'
Merging multiple models predictions.
^CTraceback (most recent call last):
  File "Inference.py", line 356, in <module>
    postprocess(mask_duplicate_dir, avg_prediction_dir)
  File "Inference.py", line 268, in postprocess
    for filename in tqdm(filenames):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 447, in __new__
    with cls._lock:
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 77, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 70, in acquire
    lock.acquire()
KeyboardInterrupt
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 887, in __del__
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 1098, in close
    if self.disable:
AttributeError: 'tqdm' object has no attribute 'disable'
^C
---------------------

**Comment by hftsai** [comment]
hah.
i see the problem.
I made a avi movie that doesn't below to it. 
it should all be only tif files in a folder to do the inference.

Please remove the T98G_sample.avi before running it.


I will figure out a better solution later.

**Comment by hiroalchem** [comment]
I removed .avi file, however same error occurred.

**Comment by hftsai** [comment]
Please make sure there should always be image files in the folder. 
I ahvent run into the inference stuck in the middle before. Which implies some problems on the tqdm or the tensorflow.

To check, can you run the inference script with just one model?
See if can generate results on your system. If not then it's something wrong with tensorflow installation.

**Comment by hiroalchem** [comment]
I am sorry that I found ".ipynb_checkpoints" was in the image directory.
I removed it and then everything worked fine!
Thank you.
