### ISSUE TITLE
 Is the journal published?

### ISSUE THREAD

**Issue by et0704a** [oist/Usiigaci#5]
Hi,

Thank you for sharing your research.
This research is useful. I want to cite the paper.

Cheers and thanks again,
et0704a

**Comment by hftsai** [comment]
Hi et0704a,
Sorry our paper is still under review after revision, and we didn't have a preprint.
In worst case you could cite the github repo.

Thank you so much for showing interest!

**Comment by et0704a** [comment]
Thank you for your prompt reply.
