### ISSUE TITLE
About Trackpy tracker

### ISSUE THREAD

**Issue by Ayanzadeh93** [oist/Usiigaci#9]
hello, 

I have a question about your tracker which is based on trackpy framework.

Have you test your method on different PCM datasets or even on different cells datasets? Is your tracker has generalized for other cell culture(especially dor PCM)?

**Comment by hftsai** [comment]
Hi 
So we are using the trackpy's default search which is the K-D tree nearest neighborhood method.

We have shown results on the glioblastoma cells and fibroblast cells. (around 6 cell types and different cells)
We have also tested a few other cancer cell lines belonging to lung cancer cells. 
So far the tracker seems to perform quite nicely. So we think it's quite generalized.

But i do think it is necessary to increase imaging interval so not too much of cell displacement that may affect the tracking. (satisfy Nyquist sampling)

we are of course planning to do some more cells that are moving much quicker such as immune cells.

if it's having bad results. You can try to adjust the weighing parameters used in the k-dimensional search.
they are in line 46-53 of the cell_tracking.py
